/**
 * Created by 刘娟娟 on 2016/6/28.
 */
export function configRouter(router){
    router.map({
        '/login':{
            name:'login',
            component:resolve=>{
                require(['../views/login.vue'],resolve)
            }
        },
        '/list':{
            name:'list',
            component:resolve=>{
                require(['../views/index.vue'],resolve)
            },
            subRoutes:{
                '/':{
                    component:resolve=>{
                        require(['../views/List.vue'],resolve)
                    }
                },
                '/auth/:userId':{
                    name:'auth',
                    component:resolve=>{
                        require(['../views/Auth.vue'],resolve)
                    }
                },
                '/dairy/:userId':{
                    name:'dairy',
                    component:resolve=>{
                        require(['../views/Dairy.vue'],resolve)
                    }
                }
            }
        }
    });
    router.redirect({
        '*': '/login'
    })
}